sudo: required
language: generic
services:
- docker
before_install:
- sudo add-apt-repository ppa:duggan/bats --yes
- sudo apt-get update -qq
- sudo apt-get install -qq bats jq
script:
- make build
- make test
deploy:
- provider: script
  script: echo "$DOCKER_USERNAME"; docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; echo "pretending to push"
  on:
    branch: "7.1"

DOCKER_USERNAME:
  secure: I48ZcnefnG63Y6Je+w2Pr37rvC3z4C6s7mbSfdrOk+7YtVlEEEyfMMyrSVucehVK9hPYrQgJYQVvpGCiW62DkJzVBBiduB/8nHYZTQH/ZWmM54sOJ1CmiqEBFER1olXJ7Spj93HPcB9Eh8wWruY6cbAxqp9khLNJkL7SV4g2KbgT0TF+X8pVo7GTOrNRZ1EP49kH8wgQpr8pYy3qLi7aXPC+I6Jew+hmtMlxRa3+CMWytz7x6luX1mteKwMVp4PjzrMEgRRWANnzFqFq59PZI/6xgXEhkD5M5/yTrrGjVq2ltPsaynNfah2/C6/ftK1exZT3P3dKAJ+WHnR5aSTAJTPv2rLnS0cIYqzCaNxZzHRJv5/tJqwavF79/0hocBZ2b0SwAr3++FUZIo27T+f8918CG39tPLkfqn0Ix2B22GG9ZE8IG6p+1DukLlQhU2KYTc179XoWU8TIxLiXKC1SoGo5lCirtWqeerJDG/l+e77vHbIoArxwDK8X/kOkzxvl1GuQ5nVwEMkigEr+vGXIgs/4rLwRTORZzx4mERFqzcVdufZn68VoH6reaOq+WYz1KwOj4zppA7GV5+FM826G/da2TAlQ/DnokgzMxvXFL0o3gTuGOQYqNgsbBtDBGvB0MZ4K4TzVnzzUF9PU+W3sApaNmJeecuEqqSJiXFTsMKo=
DOCKER_PASSWORD:
  secure: DFp0c5rrfAxvJbOwdEZ7n+SySDD+ijPzav9+rv8vRSR4DcUmufCsmvrXQXkeOsTVr4EKBjuovquD4b4lGhOhDSqHJyx0sGbIKCW56GHb69+LfGQZF4RMJJ5pBP3YtbyWHPkLG4q8fHa3MqRnACuTrLfOx9mc1+A47nOoFGLCTpQl943kNjEpJJsN/JqBHvPqSPvUDklaR2dnT+3yCcZVe+SVSR82KMO1zptEKvhzu3KuQLu7IdNT4QNfFKQI93XeulmDIDLx25IGs2uL40PBYoQ5tqgO18RIB7xPbM6wxw0MH6iqvKC7+YIMIIqgDnFnOf/BH2nFFUJLZM3iOQD9leWkndRQgXy/6XLGpRN8qRUEqhB0bBGC8kVYj8h6cDfewIvqH8l+vxBtldXK6niQfDLeQM5/pxSZL/K51ON7j+R4B0rPOLZE3Z/6ZYpdyFEA5I3dE1Vvbtw5YYo7kPcYv07qzCSKQ6HEw1Ej52IzHAJh1zDCrYtcnVns7num7wfktZTzPbWTWou8lprYXYnKle5ejKgRJU6d+JQ7gLBBTAYtdHWnfXU6R/rHsWeN/pZA9/x78a9UYWZHKqfvKpUnfjjSldVKO8WwSwLeBrPJJYcyRGUCXYCvgxQOycwc3mjOYLgOJ9VoPYnHf6E/hZVXIr2V2Yixfv+U26xooayfeNE=
